title: Archives d'un développeur. # name of the site
author: Fabien Gues # name of site's author
email: fabien.gues@protonmail.com # email of site's author
url: https://alfombra.com # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  Conseils pour monter en compétence.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "https://github.com/GrFabien/alfombra" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
designedBy: Riccardo Graziosi

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d/%m/%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag